@extends('simple-layout')
@section('content')
<div class="page">
    <h1>Twitter Posts - Service Terms</h1>
    <p>This is a binding legal contract that applies to anyone who visits this website (“Site”) and/or uses any of our services and software (“Services”). If you do not agree to all of these terms, please do not use the Site or the Services. BY ACCESSING THE SITE OR USING ANY SERVICES, YOU ARE AGREEING TO BE BOUND BY THE AGREEMENT, AS DEFINED BELOW</p>
    <h2>1. Our Agreement.</h2>
    <p>In addition to these TwitterPosts® Service Terms, your agreement with TwitterPosts also includes the specific additional terms that apply to any Service(s) you use. Throughout the Site and in all of our documentation, whenever we refer to the “Agreement” we mean these Universal Terms and the applicable additional terms. “TwitterPosts” means TwitterPosts S.L and its subsidiaries.</p>
    <h2>2. Privacy Policy.</h2>
    <p>Use of our Site and Service is subject to our Privacy Policy, located <a href="/pages/privacy/">here</a>.</p>
    <h2>3. Changes.</h2>
    <p>We are constantly evolving our Site and Services. This means that we may change, restrict or discontinue either or both, without notice or liability to you. In addition, we may change all or part of the Agreement at any time, including these Universal Terms. We may make changes by posting the changed terms on the Site. YOUR CONTINUED USE OF THE SITE AND/OR OUR SERVICES WILL CONSTITUTE ACCEPTANCE OF THE CHANGED TERMS.</p>
    <h2>4. User Content, Third-party Content and Links on the Site.</h2>
    <p>4.1. Postings You Can Make. You may post on the Site where permitted. Anything that you post to the Site will be treated as non-confidential and non-proprietary. You agree that any information, data, text, software, music, audio files or other sounds, photographs, graphics, video, messages, tags or other materials (“Content”) you post on the Site will not be offensive, harmful, abusive, illegal, obscene, pornographic, objectionable, hateful (including without limitation racist/discriminatory), threatening, encouraging of conduct that would give rise to civil or criminal liability, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise infringing or injurious to third parties. You further agree that the Content you post will not contain viruses or other mechanisms that may damage or interfere with our systems or other users’ property, will not advertise or solicit business, and will not involve political campaigning or be spam. You may not imply that your posted Content is sponsored or endorsed by us, and you will not mislead anyone as to the origin of any posted Content. We have the right, but not the obligation, to remove, edit or refuse to post Content; we do not make any commitment that we will police the Site for problems that have not been reported to us. You shall be solely responsible for all Content posted under your username and the consequences of publishing it. Without limiting any other rights in the Agreement, we may terminate a user’s access to the Site if we believe you have violated this section.</p>
    <p>4.2. Third-party Technologies. TwitterPosts may provide technologies that allow people who publish Content on third-party services to reach Site users who are interested in that Content. We make no representations or warranties regarding the performance of such third-party services, their compliance with applicable laws and regulations, or any other aspect of such third-party services. Your use of third-party services is at your own risk. You acknowledge and agree that the third-party services and any related third-party terms of service are subject to change by the applicable third-party at its sole discretion and without any notice. Furthermore, you acknowledge and agree that you are not being granted a license to (i) the third-party services; (ii) any products, services, processes or technology described in or offered by the third-party services; or (iii) any copyright, trademark, patent or other intellectual property right in the third-party services.</p>
    <p>4.3. Others’ Content and Links to Third-party Websites. We make no representations or endorsements regarding the quality, accuracy, reliability, security or condition of any third-party Content, applications or websites; you acknowledge and agree that TwitterPosts and its affiliates are not responsible for examining or evaluating the Content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of third-party materials. You are responsible for taking precautions as necessary to protect your property from viruses and other destructive mechanisms. The Site and our Services may include Content that you find offensive or otherwise objectionable, that contains inaccuracies, mistakes, or other errors, that violates the rights of third parties or that requires your agreement to additional terms and conditions (stated or unstated) in order to download, copy or use it. We do not control the Content and websites accessible through our technologies. We disclaim any responsibility for any harm resulting from your use of the Site, our Services, viewing or use of any third-party technology, Content or websites.</p>
    <p>4.4. Removal of Content. TwitterPosts reserves the right to remove any Content from the Site and Services at any time, for any reason. TwitterPosts may reformat, excerpt or translate any Content submitted by you.</p>
    <h2>5. License</h2>
    <p>5.1. Site Use. TwitterPosts grants you a limited, revocable, non-transferable and non-exclusive license to browse, place orders for Services (where applicable), and upload Content onto the Site, where permitted, for personal use, solely in accord with the terms of the Agreement. This license automatically terminates upon your breach of any of these terms.</p>
    <p>5.2. License You Grant to TwitterPosts for Content You Post on Site. When you upload any Content on the Site, you grant TwitterPosts a perpetual, irrevocable, worldwide, royalty-free license to sublicense, reproduce, adapt, modify, translate, publish, publicly perform, publicly display, create derivative works from, and distribute such Content, in any media known now or in the future. You also grant TwitterPosts the right to Use the name that you submit in connection with the Content. You represent and warrant that you own or otherwise control all of the rights to the Content that you post, that the Content is accurate and that the Use of the Content you supply does not violate our policies and will not cause injury to any person or entity.</p>
    <p>5.3. License from You for Content from Third-party Services. In addition to third-party submissions on the Site, we may display Content on the Site or your Device (as defined in the relevant EULA) directly (a) through APIs, “feeds” or other mechanisms provided by third-party services such as Twitter and (b) by accessing your accounts with such third parties as authorized by you below and during your use of the Services (“Social Content”). You acknowledge that our Use of Social Content received directly from third parties is authorized by our agreements with those third parties without need for any direct consent or license from you. As to Social Content we receive by accessing your accounts with third parties, you hereby authorize TwitterPosts to access your account for the purpose of obtaining and Using such Social Content.</p>
    <p>5.3.1. The following license applies (a) in the event that that we needed your direct consent or license to Use Social Content provided directly by third parties and (b) to all Social Content we receive by accessing your third-party accounts. You hereby grant TwitterPosts, its affiliates and Publishers a perpetual, irrevocable worldwide royalty-free right and license to “Use” all Social Content. “Use” means the exercise of all rights, including any copyright, trademark, patent, publicity or other rights, needed or beneficial for TwitterPosts, its affiliates and Publishers to operate and/or promote the Services, including any rights needed to sublicense, access, obtain, host, cache, route, transmit, store, copy, modify, distribute, perform, display, reformat, excerpt, analyze, and create algorithms from and derivative works of the Social Content, in any media known now or in the future, including by not limited to the Service as it operates across TwitterPosts’s and TwitterPosts’s affiliates’ myriad distribution platforms. “Publisher” means a third party with whom TwitterPosts has an agreement to allow the display of Social Content.</p>
    <p>5.4. You understand that we will place your Content on websites, devices, applications and other publishing platforms and mechanisms (collectively, “Properties”). Properties may include a wide variety of websites, devices, applications and other publishing platforms and mechanisms through TwitterPosts’s and TwitterPosts’s affiliates’ myriad distribution platforms. To the extent not already authorized by our agreements with third-party providers, you hereby authorize and consent to all such placements and you agree that all placements of Content shall conclusively be deemed to have been approved by you. You acknowledge that we do not offer the option of blocking Content from appearing in any specific location.</p>
    <p>5.5. We may modify (including without limitation reformat, excerpt and translate) your Content in order to transmit, display or distribute it or to meet the limitations of Publishers, networks, devices, services or media. We may also label your Content as we believe necessary to comply with any applicable law or regulation. We may also include other Content, including advertising, alongside your Content, without sharing any revenue with or accounting to you.</p>
    <p>5.6. You are solely responsible for your Content in every possible respect, including ensuring that your Content complies with your Representations and Warranties below.</p>
    <p>5.7. You understand that TwitterPosts may evaluate any website or other published materials associated with your Content, whether by automated or manual means.</p>
    <p>6. Accounts. TwitterPosts may provide the ability for you to create an account on the Site and may require, as a condition of using Services that you supply us with certain registration information. If you elect to purchase paid Services (when/if available), you agree to pay all fees and charges associated with such Services on a timely basis. We may, in our sole discretion, terminate your account or modify any account related Content or access or take any other action we deem appropriate. You are responsible for everything done through your account so please do not share your account information and password. Please notify us right away if you have lost control of your account ID or password or you suspect there is unauthorized activity in your account. You may not open a new account without our written permission if we have terminated your account or suspended your access to the Site or any Services. When your account is closed (voluntarily or involuntarily), you may no longer have access to any information or materials you store within your account. We may delete or archive these things at our discretion.</p>
    <p>7. Age. Certain services may be purchased with a credit card. If you are under 18, you may use the Site only with the involvement of a parent or guardian, and the adult will be considered the user responsible for all activities that take place. You many not use the Site if you are under 13.
    <h2>8. Things You Cannot Do.</h2>
    <p>8.1. Give false information to us or anyone else in connection with your use of the Site or the Services. This includes but is not limited to giving false information in your account registration.</p>
    <p>8.2. Use as your username a name that is offensive, vulgar, or obscene.</p>
    8.3. Interfere with anyone whose Content we display.</p>
    8.4. Open a new account without our written permission after we have terminated your account or suspended your access to the Site or any Services.</p>
    8.5. Do anything that smacks of bad online citizenship, such as spam anyone, distribute spyware or viruses, attempt to obtain password, account or private information from another TwitterPosts user, collect personal information without disclosing such and abiding by your privacy policy, harass, abuse, stalk, threaten, defame or otherwise violate the rights of any other party, or attempt to reverse engineer or hack into our systems.</p>
    8.6. Access or scrape the Site or the Services by any automated means unless you are a search engine crawling the Site for the sole purpose of creating a publicly accessible search index; or bypass any technical protections or throttling that we institute.</p>
    8.7. Copy, modify, lease, loan, sell, distribute, create derivative works from, or distribute any Content from, the Site or Services (whether the Content has been posted by us or a third- party); copy, display or use our trademarks in any way; or use the Site or Services for any purpose not explicitly authorized in the Agreement. You may, to the extent the Site and Additional EULA authorize you to do so, download or copy software accessible from the Site, for personal use only.</p>
    8.8. Link to the Site using any HTML techniques that display the Site within a frame, partial window, popup, pop-under, or any other non-standard linking method, or present or redistribute Content from the Service without our express written permission. Please contact us at partners@twitter-posts.com for further guidance.</p>
    8.9. Other than as expressly permitted through additional terms referenced in Section 1 above to which you are a party, reproduce, modify, create derivative works, distribute, sell, transfer, publicly display, publicly perform, transmit, or otherwise use the Content we make available.</p>
    8.10. Use the Site or Services if you are not legally permitted to do so (e.g., subscribe to Services if you are under 18 years of age).</p>
    8.11. Anything we ask you not to do.</p>
    <h2>9. Representations and Warranties. You represent and warrant that:</h2>
    9.1. All information you supply to TwitterPosts is complete, accurate and current.</p>
    9.2. All Social Content you have provided and will provide to or through the third-party services complies with the applicable third-party terms, rules and/or policies.</p>
    9.3. Your Content and our Use of your Content in accord with this Agreement will not violate or encourage violation of any applicable laws, regulations, code of conduct, or third-party rights (including intellectual property and privacy rights), and is not otherwise libelous, defamatory, obscene, pornographic, abusive, indecent, threatening, harassing, hateful, or offensive.</p>
    9.4. Your Content does not contain a virus, Trojan horse, worm, time bomb or other computer programming routine or engine that is intended to damage, interfere with or expropriate any system, data or information.</p>
    <h2>10. Third-party Trademarks.</h2>
    <p>All third-party trademarks are the property of their respective owners. Use of any third-party trademark or Content on the Site and/or by the Services does not constitute or imply affiliation with or endorsement of TwitterPosts by these third parties. Aside from any explicit grants in the Agreement, nothing in the Agreement grants you any license to third-party trademarks or Content.</p>
    <h2>11. Infringement.</h2>
    <p>We respect the intellectual property of others and require that our users do the same. To see our Infringement Policy or learn how to report copyright or trademark infringement, click here.</p>
    <h2>12. TwitterPosts’s Rights.</h2>
    <p>Unless otherwise specified in the Agreement and except for third-party trademarks and Content, all information and web pages appearing on this Site, including documents, services, site design, text, graphics, logos, images and icons, as well as the arrangement thereof, are the sole property of TwitterPosts. You agree that the Services contain proprietary content, information and material that is protected by applicable intellectual property and other laws, including but not limited to copyright, and that you will not use such proprietary content, information, or materials in any way whatsoever except for permitted uses of the Services. TwitterPosts retains all right, title and interest in the Site, the Services, and its trademarks, service marks and logos, including all technology and processes and any enhancements or modifications. Except for rights expressly granted in the Agreement, nothing in the Agreement grants you any right, title or license. Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner or licensee.</p>
    <h2>13. Indemnity, Disclaimers and Limits on Liability</h2>
    <p>13.1. You will indemnify, defend, and hold harmless TwitterPosts, its affiliates, officers, directors, shareholders, employees, contractors, licensors, licensees, agents, and representatives (the “Covered Entities”) against all liability, claims, costs, damages, settlements, and expenses (including interest, penalties, attorney fees and expert witness fees) (“Liabilities”) incurred by any Covered Entity in any way arising out of or relating to the Site, the Services (including without limitation the software that is a part of the Services) or the Agreement. This includes but is not limited to Liabilities arising out of or relating to your use of the Site or any Services, any use of your account by you or anyone else, any Content you receive through the Site or Services, claims of intellectual property or other third-party rights infringement, and taxes. TwitterPosts reserves the right, at your expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with our defense of such claim.</p>
    <p>13.2. TwitterPosts PROVIDES THIS SITE, THE SERVICES AND ANY SOFTWARE DOWNLOADED FROM THE SITE “AS IS” AND WITHOUT ANY WARRANTY OR CONDITION, EXPRESS, IMPLIED, OR STATUTORY. TwitterPosts SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY OF INFORMATIONAL CONTENT, AND NON-INFRINGEMENT. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THIS SITE AND THE SERVICE AND FOR ANY DOWNLOADS MADE FROM THE SITE OR SERVICES. TwitterPosts MAKES NO WARRANTY THAT THE SITE, ANY SOFTWARE DOWNLOADED FROM THE SITE OR THE SERVICE WILL MEET YOUR REQUIREMENTS OR WILL BE UNINTERRUPTED, TIMELY, SECURE, RELIABLE OR ERROR FREE, NOR DOES TwitterPosts MAKE ANY WARRANTY AS TO THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SITE OR THE SERVICE OR THAT ANY DEFECTS WILL BE CORRECTED. TwitterPosts DOES NOT WARRANT THAT SOFTWARE OPERATES ON THE TYPE OF DEVICE OWNED BY YOU AND YOU SHALL BE SOLELY RESPONSIBLE FOR OBTAINING A DEVICE COMPATIBLE WITH SOFTWARE. TwitterPosts IS NOT RESPONSIBLE FOR ANY CONTENT ACCESSED THROUGH THE SITE OR SERVICES. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM TwitterPosts SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. THIS DISCLAIMER IS MADE TO THE FULLEST EXTENT PERMITTED BY LAW. SOME STATES AND COUNTRIES DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES, SO THE FOREGOING DISCLAIMER MAY NOT APPLY TO YOU.</p>
    <p>13.3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WHATSOEVER SHALL TwitterPosts, ITS PARENT COMPANIES, AFFILIATES, OR SUPPLIERS OR THEIR RESPECTIVE EMPLOYEES, OFFICERS, SHAREHOLDERS, AGENTS, LICENSORS OR REPRESENTATIVES BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES, OR FOR ANY LOSS OF PROFITS OR REVENUE, INCLUDING BUT NOT LIMITED TO LOSS OF SALES, PROFIT, REVENUE, GOODWILL, OR DOWNTIME, OR DAMAGES FOR CONTENT, OR RELATING TO DOWNLOADING SOFTWARE, SERVICES OR POSTING CONTENT, THE INABILILTY TO USE THE SOFTWARE OR THE SERVICES, ANY CONDUCT BY A THIRD-PARTY ON, OR THIRD-PARTY CONTENT ACCESSED THROUGH, THE SITE OR SERVICES, OR ANY UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT(ARISING UNDER TORT, CONTRACT, OR OTHER LAW) REGARDLESS OF SUCH PARTY’S NEGLIGENCE OR WHETHER SUCH PARTY KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. YOU UNDERSTAND AND AGREE THAT THE DOWNLOAD AND UPLOAD OF ANY MATERIAL THROUGH THIS SITE OR THE SERVICE IS DONE AT YOUR DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY LOSS OR DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT MAY RESULT FROM THE DOWNLOAD OR UPLOAD OF ANY MATERIAL. TwitterPosts NEITHER ASSUMES, NOR DOES IT AUTHORIZE ANY OTHER PERSON TO ASSUME ON ITS BEHALF, ANY OTHER LIABILITY IN CONNECTION WITH THE PROVISION OF THE SITE OR THE SERVICE. TwitterPosts’S LIABILITY HEREUNDER IS LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW. SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
    <h2>14. Miscellaneous</h2>
    <p>14.1. We do not want to receive information that is confidential or proprietary. If you send us suggestions, Content or ideas of any kind, including potential improvements to the Site, TwitterPosts’s software and/or Services, we may use such suggestions, Content and/or ideas for any or all purposes, with no compensation or attribution to you.</p>
    <p>14.2. This Agreement will not be construed against either party as the drafter.</p>
    <p>14.3. The Agreement incorporates all TwitterPosts policies, which can be found here. We reserve the right to change our policies at any time, effective immediately.</p>
    <p>14.4. We will be entitled to recover any legal fees and other costs associated with enforcing the Agreement.</p>
    <p>14.5. We will communicate with you either by posting to a blog on the Site or on the Site itself. As stated above, the Agreement includes the Universal Terms and any additional terms that apply, as described above. The Agreement is the entire agreement between you and TwitterPosts and it replaces any other agreement between us on this subject. Aside from our right to make changes described in Section 3, any amendments to the Agreement must be in a writing signed by both parties.</p>
    <p>14.6. You cannot assign the Agreement without our written agreement. We can assign the agreement to any entity that agrees to be bound by the terms of the Agreement.</p>
    <p>14.7. If any part of the Agreement is invalid, illegal or unenforceable, that condition will not affect any other provision of the Agreement. A delay or failure to require performance of any provision will not constitute a waiver of any rights and will not impede the ability to enforce that provision later. The Agreement is the entire integrated agreement between you and TwitterPosts on this subject matter.</p>
    <p>14.8. We may grant approvals, permissions, extensions and consents by email, but any modifications by you to the Agreement must be made in a writing executed by both parties. Any notices to TwitterPosts must be sent to TwitterPosts, S.L, Avenida de los Cerezos 39, 18150, Granada, España. Attn: Member Service, with a copy sent via first class or air mail or overnight courier, and delivery is deemed given upon receipt.</p>
    <hr/>
    <p>These service terms have been update at 3th April 2017</p>
</div>
@endsection
